apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: paperclip-eitheror
  title: Paperclip EitherOr
  description: Puppet module to manage Asterisk
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: library
  owner: heroes-for-hire
  lifecycle: production
